import { Conference } from "./conference";

export const CONFERENCE: Conference[] = [
  {
    id: 1,
    nom: "conférence 1",
    image:
      "https://i0.wp.com/oyaschool.com/wp-content/uploads/2018/12/conferences15.jpg?fit=600%2C315&ssl=1",
    titre: "Conférence 1",
    description: "Album cullinan & Album poison ",
    date: "23 Juillet 2023",
    lieu: "Palais des sport-Yaounde-Cameroun",
    heure_debut: "18H30",
    heure_fin: "23H45",
    reservation_vip: "50.00Fcfa",
    reservation_classic: "10.000Fcfa",
  },
  {
    id: 2,
    nom: "conférence 2",
    image:
      "https://www.jnda2023.fr/wp-content/uploads/2022/03/jnda_0020_JNDA2020_109.jpg",
    titre: "Conférence 2",
    description: "Album  Invasion of Privacy & Album Gangsta ",
    date: "30 Juillet 2023",
    lieu: "Canal Projet-Douala-Cameroun",
    heure_debut: "16H30",
    heure_fin: "21H45",
    reservation_vip: "30.00Fcfa",
    reservation_classic: "5.000Fcfa",
  },
  {
    id: 3,
    nom: "conférence 2",
    image:
      "https://www.leral.net/photo/art/grande/70363310-49085140.jpg?v=1674656339",
    titre: " Conférence3",
    description: "Album  vol. 1 & Album Mojo trone",
    date: "20 Juillet 2023",
    lieu: "Canal Projet-Douala-Cameroun",
    heure_debut: "16H30",
    heure_fin: "21H45",
    reservation_vip: "30.00Fcfa",
    reservation_classic: "5.000Fcfa",
  },
  {
    id: 4,
    nom: "conférence 3",
    image: "https://afrique-diaspora.com/wp-content/uploads/FOJ_3771.jpg",
    titre: "Conférence 4",
    description: "Album  QUALF & Album Ipseite",
    date: "30 Juillet 2023",
    lieu: "Canal Projet-Douala-Cameroun",
    heure_debut: "16H30",
    heure_fin: "21H45",
    reservation_vip: "30.00Fcfa",
    reservation_classic: "5.000Fcfa",
  },
  {
    id: 5,
    nom: "conférence 4",
    image:
      "https://www.jnda2023.fr/wp-content/uploads/2022/03/jnda_0020_JNDA2020_109.jpg",
    titre: "Conférence 5",
    description: "Album  Massa & Album Mispa",
    date: "30 Juillet 2023",
    lieu: "Canal Projet-Douala-Cameroun",
    heure_debut: "16H30",
    heure_fin: "21H45",
    reservation_vip: "30.00Fcfa",
    reservation_classic: "5.000Fcfa",
  },
  {
    id: 6,
    nom: "conférence 6",
    image: "https://www.jnda2023.fr/wp-content/uploads/2022/04/DSC_8674.jpg",
    titre: "Conférence 6",
    description: "Album  Massa & Album Mispa",
    date: "30 Juillet 2023",
    lieu: "Canal Projet-Douala-Cameroun",
    heure_debut: "16H30",
    heure_fin: "21H45",
    reservation_vip: "30.00Fcfa",
    reservation_classic: "5.000Fcfa",
  },
  {
    id: 7,
    nom: "conférence 7",
    image: "https://www.jnda2023.fr/wp-content/uploads/2022/04/DSC_1460.jpg",
    titre: "Conférence 7",
    description: "Album  Faya & Wolowoss",
    date: "30 Juillet 2023",
    lieu: "Canal Projet-Douala-Cameroun",
    heure_debut: "16H30",
    heure_fin: "21H45",
    reservation_vip: "30.00Fcfa",
    reservation_classic: "5.000Fcfa",
  },
];
