import { Festival } from "./festival";

export const FESTIVAL: Festival[] = [
  {
    id: 1,
    nom: "Festival 1",
    image:
      "https://www.iloilotoday.com/wp-content/uploads/2022/09/dinagyang-festival.jpg",
    titre: "	Festival 1",
    description: "Album cullinan & Album poison ",
    date: "23 Juillet 2023",
    lieu: "Palais des sport-Yaounde-Cameroun",
    heure_debut: "18H30",
    heure_fin: "23H45",
    reservation_vip: "50.00Fcfa",
    reservation_classic: "10.000Fcfa",
  },
  {
    id: 2,
    nom: "Festival 2",
    image:
      "https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_640,h_480/https://www.auletch.com/wp-content/uploads/2021/10/danse-de-louest.jpg",
    titre: "	Festival 2",
    description: "Album  Invasion of Privacy & Album Gangsta ",
    date: "30 Juillet 2023",
    lieu: "Canal Projet-Douala-Cameroun",
    heure_debut: "16H30",
    heure_fin: "21H45",
    reservation_vip: "30.00Fcfa",
    reservation_classic: "5.000Fcfa",
  },
  {
    id: 3,
    nom: "Festival 3",
    image:
      "https://i2.wp.com/cameroonvoice.com/wp-content/uploads/2021/07/Festival-Afrique.jpg?resize=770%2C540&ssl=1",
    titre: "Festival 3",
    description: "Album  vol. 1 & Album Mojo trone",
    date: "20 Juillet 2023",
    lieu: "Canal Projet-Douala-Cameroun",
    heure_debut: "16H30",
    heure_fin: "21H45",
    reservation_vip: "30.00Fcfa",
    reservation_classic: "5.000Fcfa",
  },
  {
    id: 4,
    nom: "Festival 4",
    image:
      "https://i0.wp.com/www.jewanda.com/wp-content/uploads/2016/08/festival-calebasse-concours-danses-traditionnel-jewanda-.jpg?fit=640%2C399&ssl=1",
    titre: "Festival 4",
    description: "Album  QUALF & Album Ipseite",
    date: "30 Juillet 2023",
    lieu: "Canal Projet-Douala-Cameroun",
    heure_debut: "16H30",
    heure_fin: "21H45",
    reservation_vip: "30.00Fcfa",
    reservation_classic: "5.000Fcfa",
  },
  {
    id: 5,
    nom: "Festival 5",
    image:
      "https://www.festivalsfromindia.com/wp-content/uploads/2022/03/Screenshot-2022-03-05-at-11.12.18-AM.png",
    titre: "Festival 5",
    description: "Album  Massa & Album Mispa",
    date: "30 Juillet 2023",
    lieu: "Canal Projet-Douala-Cameroun",
    heure_debut: "16H30",
    heure_fin: "21H45",
    reservation_vip: "30.00Fcfa",
    reservation_classic: "5.000Fcfa",
  },
  {
    id: 6,
    nom: "Festival 6",
    image:
      "https://i0.wp.com/www.camer237.com/wp-content/uploads/2020/08/Le-Ngondo-Douala-Festival.jpg?resize=740%2C444&ssl=1",
    titre: "Festival 6",
    description: "Album  Massa & Album Mispa",
    date: "30 Juillet 2023",
    lieu: "Canal Projet-Douala-Cameroun",
    heure_debut: "16H30",
    heure_fin: "21H45",
    reservation_vip: "30.00Fcfa",
    reservation_classic: "5.000Fcfa",
  },
  {
    id: 7,
    nom: "Festival 7",
    image:
      "https://cameroonadventuresandtours.com/wp-content/uploads/2020/04/dance_bamendjou_3.jpg",
    titre: "Festival 7",
    description: "Album  Faya & Wolowoss",
    date: "30 Juillet 2023",
    lieu: "Canal Projet-Douala-Cameroun",
    heure_debut: "16H30",
    heure_fin: "21H45",
    reservation_vip: "30.00Fcfa",
    reservation_classic: "5.000Fcfa",
  },
];
